name: Django CICD

on:
  push:
    branches: [ "production" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      working-directory: ./sample_web
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      working-directory: ./sample_web
      run: |
        python manage.py test .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.8 ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        working-directory: ./sample_web
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Collect Static
        working-directory: ./sample_web
        run: |
          python manage.py collectstatic
      - name: Generate deployment package
        working-directory: ./sample_web
        run: zip -r deploy.zip . -x '*.git*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWSAccessKeyId }}
          aws_secret_key: ${{ secrets.AWSSecretKey }}
          application_name: django-example
          environment_name: django-example-dev
          version_label: app-12345
          region: ap-southeast-1
          deployment_package: ./sample_web/deploy.zip